use std::fmt::Write;
use std::fs;
use std::path::Path;

use crate::generator::model_command::ArgInfo;
use crate::generator::model_command::CommandInfo;

pub fn render(
    command: &CommandInfo,
    output_dir: &Path,
    package_name: &str,
    json_output: bool,
) -> Result<(), String> {
    let class_name = to_pascal_case(&command.name);
    let binary_name = &command.name;

    let (global_args, _): (Vec<&ArgInfo>, Vec<&ArgInfo>) =
        command.args.iter().partition(|a| !a.is_positional);

    let src_content = render_src_class(
        command,
        &class_name,
        binary_name,
        package_name,
        &global_args,
        json_output,
    );
    let vars_content = render_vars_entry(&class_name, package_name);

    let package_path = package_name.replace('.', "/");

    let src_dir = output_dir.join("src").join(&package_path);
    fs::create_dir_all(&src_dir).map_err(|err| format!("Failed to create src directory: {err}"))?;

    let src_file = src_dir.join(format!("{class_name}.groovy"));
    fs::write(&src_file, src_content)
        .map_err(|err| format!("Failed to write {}: {err}", src_file.display()))?;

    let vars_dir = output_dir.join("vars");
    fs::create_dir_all(&vars_dir)
        .map_err(|err| format!("Failed to create vars directory: {err}"))?;

    let vars_file_name = to_camel_case(&command.name);
    let vars_file = vars_dir.join(format!("{vars_file_name}.groovy"));
    fs::write(&vars_file, vars_content)
        .map_err(|err| format!("Failed to write {}: {err}", vars_file.display()))?;

    Ok(())
}

fn render_src_class(
    command: &CommandInfo,
    class_name: &str,
    binary_name: &str,
    package_name: &str,
    global_args: &[&ArgInfo],
    json_output: bool,
) -> String {
    let mut output = String::new();

    let _ = writeln!(output, "#!/usr/bin/env groovy");
    let _ = writeln!(output, "package {package_name}");
    let _ = writeln!(output);
    let _ = writeln!(output, "import groovy.transform.CompileDynamic");
    let _ = writeln!(output);

    if !command.about.is_empty() {
        let _ = writeln!(output, "/**");
        let _ = writeln!(output, " * {}", command.about);
        let _ = writeln!(output, " *");
        let _ = writeln!(output, " * Auto-generated by clapdocs --mode jenkins");
        let _ = writeln!(output, " */");
    }

    let _ = writeln!(output, "@CompileDynamic");
    let _ = writeln!(output, "class {class_name} implements Serializable {{");
    let _ = writeln!(output);
    let _ = writeln!(
        output,
        "    private static final long serialVersionUID = 1L"
    );
    let _ = writeln!(output);
    let _ = writeln!(output, "    private final Script pipeline");
    let _ = writeln!(output, "    private final String cmd");

    for arg in global_args {
        if arg.is_flag {
            let _ = writeln!(
                output,
                "    private final boolean {}",
                to_camel_case(&arg.field_name)
            );
        } else {
            let _ = writeln!(
                output,
                "    private final String {}",
                to_camel_case(&arg.field_name)
            );
        }
    }

    let _ = writeln!(output);
    render_constructor(&mut output, class_name, binary_name, global_args);
    let _ = writeln!(output);

    for sub in &command.subcommands {
        render_subcommand_method(&mut output, sub, global_args, json_output);
        let _ = writeln!(output);
    }

    if command.subcommands.is_empty() {
        render_direct_invocation_method(&mut output, command, json_output);
        let _ = writeln!(output);
    }

    render_version_method(&mut output);
    let _ = writeln!(output);
    render_exec_helpers(&mut output);

    let _ = writeln!(output, "}}");
    output
}

fn render_constructor(
    output: &mut String,
    class_name: &str,
    binary_name: &str,
    global_args: &[&ArgInfo],
) {
    let mut params = vec!["Script pipeline".to_string()];

    for arg in global_args {
        if arg.is_flag {
            let default = if arg.default.as_deref() == Some("true") {
                "true"
            } else {
                "false"
            };
            params.push(format!(
                "boolean {} = {}",
                to_camel_case(&arg.field_name),
                default
            ));
        } else if let Some(ref default) = arg.default {
            params.push(format!(
                "String {} = '{}'",
                to_camel_case(&arg.field_name),
                escape_groovy_string(default)
            ));
        } else {
            params.push(format!("String {} = null", to_camel_case(&arg.field_name)));
        }
    }

    render_signature(output, &format!("    {class_name}"), &params);

    let _ = writeln!(output, " {{");
    let _ = writeln!(output, "        this.pipeline = pipeline");
    let _ = writeln!(output, "        this.cmd = '{binary_name}'");

    for arg in global_args {
        let camel = to_camel_case(&arg.field_name);
        let _ = writeln!(output, "        this.{camel} = {camel}");
    }

    let _ = writeln!(output, "    }}");
}

fn render_subcommand_method(
    output: &mut String,
    sub: &CommandInfo,
    global_args: &[&ArgInfo],
    json_output: bool,
) {
    let method_name = to_camel_case(&sub.name);

    if !sub.about.is_empty() {
        let _ = writeln!(output, "    /**");
        let _ = writeln!(output, "     * {}", sub.about);
        let _ = writeln!(output, "     */");
    }

    let required_args: Vec<&ArgInfo> = sub.args.iter().filter(|a| a.required).collect();
    let optional_args: Vec<&ArgInfo> = sub.args.iter().filter(|a| !a.required).collect();

    let mut params = Vec::new();
    for arg in &required_args {
        let groovy_type = if arg.is_repeatable { "List" } else { "String" };
        params.push(format!("{groovy_type} {}", to_camel_case(&arg.field_name)));
    }
    if !optional_args.is_empty() {
        params.push("Map options = [:]".to_string());
    }

    let return_type = if json_output { "Map" } else { "String" };
    render_signature(output, &format!("    {return_type} {method_name}"), &params);

    let _ = writeln!(output, " {{");

    let _ = writeln!(output, "        List command = [this.cmd]");
    let _ = writeln!(output);

    render_global_args_assembly(output, global_args);

    let _ = writeln!(output, "        command.add('{}')", sub.name);
    let _ = writeln!(output);

    for arg in &required_args {
        let camel = to_camel_case(&arg.field_name);
        if arg.is_positional {
            if arg.is_repeatable {
                let _ = writeln!(output, "        {camel}.each {{ entry ->");
                let _ = writeln!(output, "            command.add(entry)");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        command.add({camel})");
            }
        } else if let Some(ref long) = arg.long_name {
            if arg.is_repeatable {
                let _ = writeln!(output, "        {camel}.each {{ entry ->");
                let _ = writeln!(output, "            command.add('--{long}')");
                let _ = writeln!(output, "            command.add(entry)");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        command.add('--{long}')");
                let _ = writeln!(output, "        command.add({camel})");
            }
        }
    }

    if !optional_args.is_empty() {
        let _ = writeln!(output);
        for arg in &optional_args {
            let camel = to_camel_case(&arg.field_name);
            if let Some(ref long) = arg.long_name {
                if arg.is_flag {
                    let _ = writeln!(output, "        if (options.get('{camel}')) {{");
                    let _ = writeln!(output, "            command.add('--{long}')");
                    let _ = writeln!(output, "        }}");
                } else if arg.is_repeatable {
                    let _ = writeln!(output, "        if (options.get('{camel}') != null) {{");
                    let _ = writeln!(
                        output,
                        "            options.get('{camel}').each {{ entry ->"
                    );
                    let _ = writeln!(output, "                command.add('--{long}')");
                    let _ = writeln!(output, "                command.add(entry)");
                    let _ = writeln!(output, "            }}");
                    let _ = writeln!(output, "        }}");
                } else {
                    let _ = writeln!(output, "        if (options.get('{camel}') != null) {{");
                    let _ = writeln!(output, "            command.add('--{long}')");
                    let _ = writeln!(
                        output,
                        "            command.add(options.get('{camel}').toString())"
                    );
                    let _ = writeln!(output, "        }}");
                }
            }
        }
    }

    let _ = writeln!(output);
    let exec_call = if json_output { "execJson" } else { "exec" };
    let _ = writeln!(output, "        return {exec_call}(command)");
    let _ = writeln!(output, "    }}");
}

fn render_direct_invocation_method(output: &mut String, command: &CommandInfo, json_output: bool) {
    let required_args: Vec<&ArgInfo> = command.args.iter().filter(|a| a.required).collect();
    let optional_args: Vec<&ArgInfo> = command
        .args
        .iter()
        .filter(|a| !a.required && !a.is_positional)
        .collect();

    let mut params = Vec::new();
    for arg in &required_args {
        let groovy_type = if arg.is_repeatable { "List" } else { "String" };
        params.push(format!("{groovy_type} {}", to_camel_case(&arg.field_name)));
    }
    if !optional_args.is_empty() {
        params.push("Map options = [:]".to_string());
    }

    let return_type = if json_output { "Map" } else { "String" };
    render_signature(output, &format!("    {return_type} run"), &params);

    let _ = writeln!(output, " {{");

    let _ = writeln!(output, "        List command = [this.cmd]");

    for arg in &required_args {
        let camel = to_camel_case(&arg.field_name);
        if arg.is_positional {
            if arg.is_repeatable {
                let _ = writeln!(output, "        {camel}.each {{ entry ->");
                let _ = writeln!(output, "            command.add(entry)");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        command.add({camel})");
            }
        } else if let Some(ref long) = arg.long_name {
            if arg.is_repeatable {
                let _ = writeln!(output, "        {camel}.each {{ entry ->");
                let _ = writeln!(output, "            command.add('--{long}')");
                let _ = writeln!(output, "            command.add(entry)");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        command.add('--{long}')");
                let _ = writeln!(output, "        command.add({camel})");
            }
        }
    }

    if !optional_args.is_empty() {
        for arg in &optional_args {
            let camel = to_camel_case(&arg.field_name);
            if let Some(ref long) = arg.long_name {
                if arg.is_flag {
                    let _ = writeln!(output, "        if (options.get('{camel}')) {{");
                    let _ = writeln!(output, "            command.add('--{long}')");
                    let _ = writeln!(output, "        }}");
                } else if arg.is_repeatable {
                    let _ = writeln!(output, "        if (options.get('{camel}') != null) {{");
                    let _ = writeln!(
                        output,
                        "            options.get('{camel}').each {{ entry ->"
                    );
                    let _ = writeln!(output, "                command.add('--{long}')");
                    let _ = writeln!(output, "                command.add(entry)");
                    let _ = writeln!(output, "            }}");
                    let _ = writeln!(output, "        }}");
                } else {
                    let _ = writeln!(output, "        if (options.get('{camel}') != null) {{");
                    let _ = writeln!(output, "            command.add('--{long}')");
                    let _ = writeln!(
                        output,
                        "            command.add(options.get('{camel}').toString())"
                    );
                    let _ = writeln!(output, "        }}");
                }
            }
        }
    }

    let _ = writeln!(output);
    let exec_call = if json_output { "execJson" } else { "exec" };
    let _ = writeln!(output, "        return {exec_call}(command)");
    let _ = writeln!(output, "    }}");
}

fn render_global_args_assembly(output: &mut String, global_args: &[&ArgInfo]) {
    for arg in global_args {
        let camel = to_camel_case(&arg.field_name);
        if let Some(ref long) = arg.long_name {
            if arg.is_flag {
                let _ = writeln!(output, "        if (this.{camel}) {{");
                let _ = writeln!(output, "            command.add('--{long}')");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        if (this.{camel} != null) {{");
                let _ = writeln!(output, "            command.add('--{long}')");
                let _ = writeln!(output, "            command.add(this.{camel})");
                let _ = writeln!(output, "        }}");
            }
        }
    }

    if !global_args.is_empty() {
        let _ = writeln!(output);
    }
}

fn render_version_method(output: &mut String) {
    let _ = writeln!(output, "    String version() {{");
    let _ = writeln!(output, "        return this.pipeline.sh(");
    let _ = writeln!(output, "            script: \"${{this.cmd}} --version\",");
    let _ = writeln!(output, "            returnStdout: true");
    let _ = writeln!(output, "        ).trim()");
    let _ = writeln!(output, "    }}");
}

fn render_exec_helpers(output: &mut String) {
    let _ = writeln!(output, "    private String exec(List command) {{");
    let _ = writeln!(output, "        return this.pipeline.sh(");
    let _ = writeln!(output, "            script: command.join(' '),");
    let _ = writeln!(output, "            returnStdout: true");
    let _ = writeln!(output, "        ).trim()");
    let _ = writeln!(output, "    }}");
    let _ = writeln!(output);
    let _ = writeln!(output, "    private int execStatus(List command) {{");
    let _ = writeln!(output, "        return this.pipeline.sh(");
    let _ = writeln!(output, "            script: command.join(' '),");
    let _ = writeln!(output, "            returnStatus: true");
    let _ = writeln!(output, "        )");
    let _ = writeln!(output, "    }}");
    let _ = writeln!(output);
    let _ = writeln!(output, "    private Map execJson(List command) {{");
    let _ = writeln!(output, "        String json = exec(command)");
    let _ = writeln!(output, "        return this.pipeline.readJSON(text: json)");
    let _ = writeln!(output, "    }}");
}

fn render_vars_entry(class_name: &str, package_name: &str) -> String {
    let mut output = String::new();
    let _ = writeln!(output, "#!/usr/bin/env groovy");
    let _ = writeln!(output);
    let _ = writeln!(output, "import {package_name}.{class_name}");
    let _ = writeln!(output);
    let _ = writeln!(
        output,
        "{class_name} call(Script pipeline, Map config = [:]) {{"
    );
    let _ = writeln!(output, "    return new {class_name}(pipeline, *:config)");
    let _ = writeln!(output, "}}");
    output
}

fn render_signature(output: &mut String, prefix: &str, params: &[String]) {
    let inline = format!("{}({})", prefix, params.join(", "));
    let max_line_length = 120;

    if inline.len() + 2 <= max_line_length {
        let _ = write!(output, "{inline}");
    } else {
        let indent = " ".repeat(prefix.len() - prefix.trim_start().len() + 8);
        let _ = writeln!(output, "{}(", prefix);
        for (index, param) in params.iter().enumerate() {
            let _ = write!(output, "{indent}{param}");
            if index < params.len() - 1 {
                let _ = writeln!(output, ",");
            }
        }
        let _ = write!(
            output,
            "\n{})",
            " ".repeat(prefix.len() - prefix.trim_start().len())
        );
    }
}

fn to_pascal_case(name: &str) -> String {
    name.split(['-', '_'])
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            let first = chars.next().unwrap_or_default().to_uppercase().to_string();
            first + chars.as_str()
        })
        .collect()
}

fn to_camel_case(name: &str) -> String {
    let pascal = to_pascal_case(name);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn escape_groovy_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}
