use std::fmt::Write;
use std::fs;
use std::path::Path;

use crate::generator::model_command::ArgInfo;
use crate::generator::model_command::CommandInfo;
use crate::generator::model_command::ExecutionModel;

pub fn render(
    command: &CommandInfo,
    output_dir: &Path,
    package_name: &str,
    execution_model: ExecutionModel,
    json_output: bool,
    stubs: bool,
) -> Result<(), String> {
    let _stubs = stubs; //TODO: implement stub creation when this flag is true

    let class_name = to_pascal_case(&command.name);
    let binary_name = &command.name;

    let (global_args, _): (Vec<&ArgInfo>, Vec<&ArgInfo>) =
        command.args.iter().partition(|a| !a.is_positional);

    let src_content = render_src_class(
        command,
        &class_name,
        binary_name,
        package_name,
        &global_args,
        execution_model,
        json_output,
    );
    let vars_content = render_vars_entry(&class_name, package_name, &global_args, execution_model);

    let package_path = package_name.replace('.', "/");

    let src_dir = output_dir.join("src").join(&package_path);
    fs::create_dir_all(&src_dir).map_err(|err| format!("Failed to create src directory: {err}"))?;

    let src_file = src_dir.join(format!("{class_name}.groovy"));
    fs::write(&src_file, src_content)
        .map_err(|err| format!("Failed to write {}: {err}", src_file.display()))?;

    let vars_dir = output_dir.join("vars");
    fs::create_dir_all(&vars_dir)
        .map_err(|err| format!("Failed to create vars directory: {err}"))?;

    let vars_file_name = to_camel_case(&command.name);
    let vars_file = vars_dir.join(format!("{vars_file_name}.groovy"));
    fs::write(&vars_file, vars_content)
        .map_err(|err| format!("Failed to write {}: {err}", vars_file.display()))?;

    Ok(())
}

fn render_src_class(
    command: &CommandInfo,
    class_name: &str,
    binary_name: &str,
    package_name: &str,
    global_args: &[&ArgInfo],
    execution_model: ExecutionModel,
    json_output: bool,
) -> String {
    let mut output = String::new();

    let _ = writeln!(output, "#!/usr/bin/env groovy");
    let _ = writeln!(output, "package {package_name}");
    let _ = writeln!(output);
    let _ = writeln!(output, "import groovy.transform.CompileDynamic");
    if execution_model == ExecutionModel::Jvm {
        let _ = writeln!(output, "import groovy.json.JsonSlurper");
    }
    let _ = writeln!(output);

    if !command.about.is_empty() {
        let _ = writeln!(output, "/**");
        let _ = writeln!(output, " * {}", command.about);
        let _ = writeln!(output, " *");
        let _ = writeln!(output, " * Auto-generated by `clapdocs jenkins`");
        let _ = writeln!(output, " */");
    }

    let _ = writeln!(output, "@CompileDynamic");
    let _ = writeln!(output, "class {class_name} implements Serializable {{");
    let _ = writeln!(output);
    let _ = writeln!(
        output,
        "    private static final long serialVersionUID = 1L"
    );
    let _ = writeln!(output);
    if execution_model != ExecutionModel::Jvm {
        let _ = writeln!(output, "    private final Script pipeline");
    }
    let _ = writeln!(output, "    private final String cmd");

    for arg in global_args {
        if arg.is_flag {
            let _ = writeln!(
                output,
                "    private final boolean {}",
                to_camel_case(&arg.field_name)
            );
        } else {
            let _ = writeln!(
                output,
                "    private final Object {}",
                to_camel_case(&arg.field_name)
            );
        }
    }

    let _ = writeln!(output);
    render_constructor(
        &mut output,
        class_name,
        binary_name,
        global_args,
        execution_model,
    );
    let _ = writeln!(output);

    for sub in &command.subcommands {
        render_subcommand_method(&mut output, sub, global_args, json_output);
        let _ = writeln!(output);
    }

    if command.subcommands.is_empty() {
        render_direct_invocation_method(&mut output, command, json_output);
        let _ = writeln!(output);
    }

    render_version_method(&mut output, execution_model);
    let _ = writeln!(output);
    render_exec_helpers(&mut output, execution_model);

    let _ = writeln!(output, "}}");
    output
}

fn render_constructor(
    output: &mut String,
    class_name: &str,
    binary_name: &str,
    global_args: &[&ArgInfo],
    execution_model: ExecutionModel,
) {
    let mut params = Vec::new();
    if execution_model != ExecutionModel::Jvm {
        params.push("Script pipeline".to_string());
    }

    for arg in global_args {
        let groovy_type = if arg.is_flag { "boolean" } else { "Object" };
        params.push(format!(
            "{groovy_type} {} = {}",
            to_camel_case(&arg.field_name),
            arg_default_literal(arg)
        ));
    }

    render_signature(output, &format!("    {class_name}"), &params);

    let _ = writeln!(output, " {{");
    if execution_model != ExecutionModel::Jvm {
        let _ = writeln!(output, "        this.pipeline = pipeline");
    }
    let _ = writeln!(output, "        this.cmd = '{binary_name}'");

    for arg in global_args {
        let camel = to_camel_case(&arg.field_name);
        let _ = writeln!(output, "        this.{camel} = {camel}");
    }

    let _ = writeln!(output, "    }}");
}

fn render_subcommand_method(
    output: &mut String,
    sub: &CommandInfo,
    global_args: &[&ArgInfo],
    json_output: bool,
) {
    let method_name = to_camel_case(&sub.name);

    if !sub.about.is_empty() {
        let _ = writeln!(output, "    /**");
        let _ = writeln!(output, "     * {}", sub.about);
        let _ = writeln!(output, "     */");
    }

    let required_args: Vec<&ArgInfo> = sub.args.iter().filter(|a| a.required).collect();
    let optional_args: Vec<&ArgInfo> = sub.args.iter().filter(|a| !a.required).collect();

    let mut params = Vec::new();
    for arg in &required_args {
        let groovy_type = if arg.is_repeatable { "List" } else { "Object" };
        params.push(format!("{groovy_type} {}", to_camel_case(&arg.field_name)));
    }
    if !optional_args.is_empty() {
        params.push("Map options = [:]".to_string());
    }

    let return_type = if json_output { "Map" } else { "String" };
    render_signature(output, &format!("    {return_type} {method_name}"), &params);

    let _ = writeln!(output, " {{");

    let _ = writeln!(output, "        List command = [this.cmd]");
    let _ = writeln!(output);

    render_global_args_assembly(output, global_args);

    let _ = writeln!(output, "        command.add('{}')", sub.name);
    let _ = writeln!(output);

    for arg in &required_args {
        let camel = to_camel_case(&arg.field_name);
        if arg.is_positional {
            if arg.is_repeatable {
                let _ = writeln!(output, "        {camel}.each {{ entry ->");
                let _ = writeln!(output, "            command.add(entry.toString())");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        command.add({camel}.toString())");
            }
        } else if let Some(token) = arg_flag_token(arg) {
            if arg.is_count {
                render_count_arg_assembly(output, &camel, &camel, &token);
            } else if arg.is_repeatable {
                let _ = writeln!(output, "        {camel}.each {{ entry ->");
                let _ = writeln!(output, "            command.add('{token}')");
                let _ = writeln!(output, "            command.add(entry.toString())");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        command.add('{token}')");
                let _ = writeln!(output, "        command.add({camel}.toString())");
            }
        }
    }

    if !optional_args.is_empty() {
        let _ = writeln!(output);
        for arg in &optional_args {
            let camel = to_camel_case(&arg.field_name);
            let Some(token) = arg_flag_token(arg) else {
                continue;
            };
            let accessor = format!("options.get('{camel}')");

            if arg.is_count {
                render_count_arg_assembly(output, &camel, &accessor, &token);
            } else if arg.is_flag {
                let _ = writeln!(output, "        if ({accessor}) {{");
                let _ = writeln!(output, "            command.add('{token}')");
                let _ = writeln!(output, "        }}");
            } else if arg.is_repeatable {
                let _ = writeln!(output, "        if ({accessor} != null) {{");
                let _ = writeln!(output, "            {accessor}.each {{ entry ->");
                let _ = writeln!(output, "                command.add('{token}')");
                let _ = writeln!(output, "                command.add(entry.toString())");
                let _ = writeln!(output, "            }}");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        if ({accessor} != null) {{");
                let _ = writeln!(output, "            command.add('{token}')");
                let _ = writeln!(output, "            command.add({accessor}.toString())");
                let _ = writeln!(output, "        }}");
            }
        }
    }

    let _ = writeln!(output);
    let exec_call = if json_output { "execJson" } else { "exec" };
    let _ = writeln!(output, "        return {exec_call}(command)");
    let _ = writeln!(output, "    }}");
}

fn render_direct_invocation_method(output: &mut String, command: &CommandInfo, json_output: bool) {
    let required_args: Vec<&ArgInfo> = command.args.iter().filter(|a| a.required).collect();
    let optional_args: Vec<&ArgInfo> = command
        .args
        .iter()
        .filter(|a| !a.required && !a.is_positional)
        .collect();

    let mut params = Vec::new();
    for arg in &required_args {
        let groovy_type = if arg.is_repeatable { "List" } else { "Object" };
        params.push(format!("{groovy_type} {}", to_camel_case(&arg.field_name)));
    }
    if !optional_args.is_empty() {
        params.push("Map options = [:]".to_string());
    }

    let return_type = if json_output { "Map" } else { "String" };
    render_signature(output, &format!("    {return_type} run"), &params);

    let _ = writeln!(output, " {{");

    let _ = writeln!(output, "        List command = [this.cmd]");

    for arg in &required_args {
        let camel = to_camel_case(&arg.field_name);
        if arg.is_positional {
            if arg.is_repeatable {
                let _ = writeln!(output, "        {camel}.each {{ entry ->");
                let _ = writeln!(output, "            command.add(entry.toString())");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        command.add({camel}.toString())");
            }
        } else if let Some(token) = arg_flag_token(arg) {
            if arg.is_count {
                render_count_arg_assembly(output, &camel, &camel, &token);
            } else if arg.is_repeatable {
                let _ = writeln!(output, "        {camel}.each {{ entry ->");
                let _ = writeln!(output, "            command.add('{token}')");
                let _ = writeln!(output, "            command.add(entry.toString())");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        command.add('{token}')");
                let _ = writeln!(output, "        command.add({camel}.toString())");
            }
        }
    }

    if !optional_args.is_empty() {
        for arg in &optional_args {
            let camel = to_camel_case(&arg.field_name);
            let Some(token) = arg_flag_token(arg) else {
                continue;
            };
            let accessor = format!("options.get('{camel}')");

            if arg.is_count {
                render_count_arg_assembly(output, &camel, &accessor, &token);
            } else if arg.is_flag {
                let _ = writeln!(output, "        if ({accessor}) {{");
                let _ = writeln!(output, "            command.add('{token}')");
                let _ = writeln!(output, "        }}");
            } else if arg.is_repeatable {
                let _ = writeln!(output, "        if ({accessor} != null) {{");
                let _ = writeln!(output, "            {accessor}.each {{ entry ->");
                let _ = writeln!(output, "                command.add('{token}')");
                let _ = writeln!(output, "                command.add(entry.toString())");
                let _ = writeln!(output, "            }}");
                let _ = writeln!(output, "        }}");
            } else {
                let _ = writeln!(output, "        if ({accessor} != null) {{");
                let _ = writeln!(output, "            command.add('{token}')");
                let _ = writeln!(output, "            command.add({accessor}.toString())");
                let _ = writeln!(output, "        }}");
            }
        }
    }

    let _ = writeln!(output);
    let exec_call = if json_output { "execJson" } else { "exec" };
    let _ = writeln!(output, "        return {exec_call}(command)");
    let _ = writeln!(output, "    }}");
}

fn arg_flag_token(arg: &ArgInfo) -> Option<String> {
    if let Some(ref long) = arg.long_name {
        Some(format!("--{long}"))
    } else {
        arg.short_name.map(|short| format!("-{short}"))
    }
}

fn render_count_arg_assembly(output: &mut String, camel: &str, accessor: &str, token: &str) {
    let _ = writeln!(output, "        if ({accessor}) {{");
    let _ = writeln!(output, "            int {camel}Count = 1");
    let _ = writeln!(output, "            if ({accessor} instanceof Number) {{");
    let _ = writeln!(
        output,
        "                {camel}Count = ({accessor}).intValue()"
    );
    let _ = writeln!(
        output,
        "            }} else if ({accessor} instanceof CharSequence && ({accessor}).isInteger()) {{"
    );
    let _ = writeln!(
        output,
        "                {camel}Count = ({accessor}).toInteger()"
    );
    let _ = writeln!(output, "            }}");
    let _ = writeln!(
        output,
        "            {camel}Count.times {{ command.add('{token}') }}"
    );
    let _ = writeln!(output, "        }}");
}

fn render_global_args_assembly(output: &mut String, global_args: &[&ArgInfo]) {
    for arg in global_args {
        let camel = to_camel_case(&arg.field_name);
        let Some(token) = arg_flag_token(arg) else {
            continue;
        };
        let accessor = format!("this.{camel}");

        if arg.is_count {
            render_count_arg_assembly(output, &camel, &accessor, &token);
        } else if arg.is_flag {
            let _ = writeln!(output, "        if ({accessor}) {{");
            let _ = writeln!(output, "            command.add('{token}')");
            let _ = writeln!(output, "        }}");
        } else {
            let _ = writeln!(output, "        if ({accessor} != null) {{");
            let _ = writeln!(output, "            command.add('{token}')");
            let _ = writeln!(output, "            command.add({accessor}.toString())");
            let _ = writeln!(output, "        }}");
        }
    }

    if !global_args.is_empty() {
        let _ = writeln!(output);
    }
}

fn render_version_method(output: &mut String, execution_model: ExecutionModel) {
    if let Some(step) = pipeline_step_name(execution_model) {
        let _ = writeln!(output, "    String version() {{");
        let _ = writeln!(output, "        return this.pipeline.{step}(");
        let _ = writeln!(output, "            script: \"${{this.cmd}} --version\",");
        let _ = writeln!(output, "            returnStdout: true");
        let _ = writeln!(output, "        ).trim()");
        let _ = writeln!(output, "    }}");
        return;
    }

    let _ = writeln!(output, "    String version() {{");
    let _ = writeln!(output, "        return exec([this.cmd, '--version'])");
    let _ = writeln!(output, "    }}");
}

fn render_exec_helpers(output: &mut String, execution_model: ExecutionModel) {
    if let Some(step) = pipeline_step_name(execution_model) {
        let _ = writeln!(output, "    private String exec(List command) {{");
        let _ = writeln!(output, "        return this.pipeline.{step}(");
        let _ = writeln!(output, "            script: command.join(' '),");
        let _ = writeln!(output, "            returnStdout: true");
        let _ = writeln!(output, "        ).trim()");
        let _ = writeln!(output, "    }}");
        let _ = writeln!(output);
        let _ = writeln!(output, "    private int execStatus(List command) {{");
        let _ = writeln!(output, "        return this.pipeline.{step}(");
        let _ = writeln!(output, "            script: command.join(' '),");
        let _ = writeln!(output, "            returnStatus: true");
        let _ = writeln!(output, "        )");
        let _ = writeln!(output, "    }}");
        let _ = writeln!(output);
        let _ = writeln!(output, "    private Map execJson(List command) {{");
        let _ = writeln!(output, "        String json = exec(command)");
        let _ = writeln!(output, "        return this.pipeline.readJSON(text: json)");
        let _ = writeln!(output, "    }}");
        return;
    }

    let _ = writeln!(output, "    private String exec(List<String> command) {{");
    let _ = writeln!(
        output,
        "        Process process = new ProcessBuilder(command).start()"
    );
    let _ = writeln!(output, "        StringBuilder stdout = new StringBuilder()");
    let _ = writeln!(output, "        StringBuilder stderr = new StringBuilder()");
    let _ = writeln!(
        output,
        "        process.waitForProcessOutput(stdout, stderr)"
    );
    let _ = writeln!(output, "        int exitCode = process.exitValue()");
    let _ = writeln!(output, "        if (exitCode != 0) {{");
    let _ = writeln!(
        output,
        "            throw new RuntimeException(\"Command failed (exit ${{exitCode}}): ${{stderr}}\")"
    );
    let _ = writeln!(output, "        }}");
    let _ = writeln!(output, "        return stdout.toString().trim()");
    let _ = writeln!(output, "    }}");
    let _ = writeln!(output);
    let _ = writeln!(
        output,
        "    private int execStatus(List<String> command) {{"
    );
    let _ = writeln!(
        output,
        "        Process process = new ProcessBuilder(command).start()"
    );
    let _ = writeln!(
        output,
        "        process.waitForProcessOutput(new StringBuilder(), new StringBuilder())"
    );
    let _ = writeln!(output, "        return process.exitValue()");
    let _ = writeln!(output, "    }}");
    let _ = writeln!(output);
    let _ = writeln!(output, "    private Map execJson(List<String> command) {{");
    let _ = writeln!(output, "        String json = exec(command)");
    let _ = writeln!(
        output,
        "        return new JsonSlurper().parseText(json) as Map"
    );
    let _ = writeln!(output, "    }}");
}

/// Returns the Jenkins pipeline step name backing `sh`/`ps`/`bat` execution
/// models, or `None` for `jvm` (which has no pipeline step dependency).
fn pipeline_step_name(execution_model: ExecutionModel) -> Option<&'static str> {
    match execution_model {
        ExecutionModel::Sh => Some("sh"),
        ExecutionModel::Ps => Some("powershell"),
        ExecutionModel::Bat => Some("bat"),
        ExecutionModel::Jvm => None,
    }
}

fn render_vars_entry(
    class_name: &str,
    package_name: &str,
    global_args: &[&ArgInfo],
    execution_model: ExecutionModel,
) -> String {
    let mut output = String::new();
    let _ = writeln!(output, "#!/usr/bin/env groovy");
    let _ = writeln!(output);
    let _ = writeln!(output, "import {package_name}.{class_name}");
    let _ = writeln!(output);

    let mut ctor_args = Vec::new();
    if execution_model != ExecutionModel::Jvm {
        ctor_args.push("pipeline".to_string());
    }
    for arg in global_args {
        let camel = to_camel_case(&arg.field_name);
        ctor_args.push(format!(
            "config.get('{camel}', {})",
            arg_default_literal(arg)
        ));
    }

    if execution_model == ExecutionModel::Jvm {
        let _ = writeln!(output, "{class_name} call(Map config = [:]) {{");
    } else {
        let _ = writeln!(
            output,
            "{class_name} call(Script pipeline, Map config = [:]) {{"
        );
    }
    render_signature(
        &mut output,
        &format!("    return new {class_name}"),
        &ctor_args,
    );
    let _ = writeln!(output);
    let _ = writeln!(output, "}}");
    output
}

fn render_signature(output: &mut String, prefix: &str, params: &[String]) {
    let inline = format!("{}({})", prefix, params.join(", "));
    let max_line_length = 120;

    if inline.len() + 2 <= max_line_length {
        let _ = write!(output, "{inline}");
    } else {
        let indent = " ".repeat(prefix.len() - prefix.trim_start().len() + 8);
        let _ = writeln!(output, "{}(", prefix);
        for (index, param) in params.iter().enumerate() {
            let _ = write!(output, "{indent}{param}");
            if index < params.len() - 1 {
                let _ = writeln!(output, ",");
            }
        }
        let _ = write!(
            output,
            "\n{})",
            " ".repeat(prefix.len() - prefix.trim_start().len())
        );
    }
}

fn to_pascal_case(name: &str) -> String {
    name.split(['-', '_'])
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            let first = chars.next().unwrap_or_default().to_uppercase().to_string();
            first + chars.as_str()
        })
        .collect()
}

fn to_camel_case(name: &str) -> String {
    let pascal = to_pascal_case(name);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn arg_default_literal(arg: &ArgInfo) -> String {
    if arg.is_flag {
        if arg.default.as_deref() == Some("true") {
            "true".to_string()
        } else {
            "false".to_string()
        }
    } else if let Some(ref default) = arg.default {
        format!("'{}'", escape_groovy_string(default))
    } else {
        "null".to_string()
    }
}

fn escape_groovy_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}
